export const GET_CURRENCY_OPTIONS = 'GET_CURRENCY_OPTIONS';
export const CURRENCY_1_CHANGE = 'CURRENCY_1_CHANGE';
export const CURRENCY_2_CHANGE = 'CURRENCY_2_CHANGE';
export const GET_EX_RATE = 'GET_EX_RATE';
